/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apk_pengaduan_masyarakat;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JFileChooser;
import java.awt.*;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author bri gunjat
 */
public class Laporan_Pengaduan extends javax.swing.JFrame {
 Connection con;
    DefaultTableModel tm;
    
    public void connect(){
        con=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/pengaduan_masyarakat","root","");
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
        }
    }
    
    private void id_otomatis() {
        try {
            Connection c = con;
            Statement s = c.createStatement();
            String sql = "SELECT * From pengaduan ORDER BY id_pengaduan DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String No = r.getString("id_pengaduan");
                String otomatis = "" + (Integer.parseInt(No) + 1);
                IP.setText(otomatis);
            } else {
                IP.setText("1");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println("autonumber error");
        }
    }
    
    private void read_table(){
       tm=new DefaultTableModel (null,
    new Object [] {"id_pengaduan","tgl_pengaduan","nik","isi_laporan","foto","status"});
    TabelP.setModel(tm);
    tm.getDataVector().removeAllElements();
    try{
        
        PreparedStatement s = con.prepareStatement("SELECT * FROM pengaduan");
        ResultSet r = s.executeQuery();
        while(r.next()){
            Object[] data={
               r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                 r.getString(5),
                  r.getString(6)
            };
            tm.addRow(data);
        }
    }catch (Exception e){
        System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
    
    }
    }
        
        public void cbn(){
            try {
                PreparedStatement s=con.prepareStatement("SELECT*FROM masyarakat WHERE nik");
                ResultSet r=s.executeQuery();
                while (r.next()){
                    CBN.addItem(r.getString("nik"));
            }
        } catch (SQLException e) {
    }
        }
    
    
    /**
     * Creates new form Laporan_Pengaduan
     */
    public Laporan_Pengaduan() {
        initComponents();
         connect();
        id_otomatis();
        read_table();
        cbn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TP = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IL = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        CBN = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        FOTO = new javax.swing.JLabel();
        BTNIF = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CBS = new javax.swing.JComboBox<>();
        BTNU = new javax.swing.JButton();
        BTND = new javax.swing.JButton();
        BTNE = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        BTNS2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelP = new javax.swing.JTable();
        F = new javax.swing.JTextField();
        BTNS1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LAPORAN PENGADUAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("ID PENGADUAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("TGL PENGADUAN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("ISI LAPORAN");

        IL.setColumns(20);
        IL.setRows(5);
        jScrollPane1.setViewportView(IL);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("NIK");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("FOTO");

        FOTO.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        FOTO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FOTO.setText("FOTO");
        FOTO.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        FOTO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BTNIF.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNIF.setText("IMPORT FOTO");
        BTNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("STATUS");

        CBS.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CBS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "PROSES", "SELESAI" }));

        BTNU.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNU.setText("UPDATE");
        BTNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUActionPerformed(evt);
            }
        });

        BTND.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTND.setText("DELETE");
        BTND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDActionPerformed(evt);
            }
        });

        BTNE.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNE.setText("EXIT");
        BTNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEActionPerformed(evt);
            }
        });

        BTNS2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNS2.setText("SEARCH");

        TabelP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelP);

        BTNS1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNS1.setText("SAVE");
        BTNS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNS1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(IP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBN, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CBS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNIF)
                                .addGap(60, 60, 60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BTNS1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNU)
                        .addGap(18, 18, 18)
                        .addComponent(BTND)
                        .addGap(18, 18, 18)
                        .addComponent(BTNE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNS2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(CBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(FOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNIF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNS1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTND)
                        .addComponent(BTNE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNS2)
                        .addComponent(BTNU)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(606, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIFActionPerformed
        // TODO add your handling code here:
          String filename=null;
        JFileChooser chooser =new JFileChooser("");
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        F.setText(filename);
        Image getAbsolutePath=null;
        ImageIcon icon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(FOTO.getWidth(),
            FOTO.getHeight(),Image.SCALE_SMOOTH));
    FOTO.setIcon(icon);
    }//GEN-LAST:event_BTNIFActionPerformed

    private void TabelPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPMouseClicked
        // TODO add your handling code here:
         int i = TabelP.getSelectedRow();
        if (i == -1){
            return;
        }
        String idpengaduan = (String) tm.getValueAt(i, 0);
        IP.setText(idpengaduan);
        String tglpengaduan = (String) tm.getValueAt(i, 1);
        TP.setDateFormatString(tglpengaduan);
        String nik = (String) tm.getValueAt(i, 2);
        CBN.setActionCommand(nik);
        String isilaporan = (String) tm.getValueAt(i, 3);
        IL.setText(isilaporan);
        String foto = (String) tm.getValueAt(i, 4);
        F.setText(foto);
        String status = (String) tm.getValueAt(i, 5);
        CBS.setActionCommand(status);
    }//GEN-LAST:event_TabelPMouseClicked

    private void BTNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUActionPerformed
        // TODO add your handling code here:
        String Tampilan="yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(Tampilan);
        String tglbyr=String.valueOf(fm.format(TP.getDate()));
        try{
            PreparedStatement ps=con.prepareStatement("UPDATE pengaduan SET tgl_pengaduan=?,nik=?,isi_laporan=?,foto=?,status=? WHERE id_pengaduan=?");
            ps.setString(1, tglbyr);
            ps.setString(2, CBN.getSelectedItem().toString());
            ps.setString(3, IL.getText());
             ps.setString(4, F.getText());
             ps.setString(5, CBS.getSelectedItem().toString());
              ps.setString(6, IP.getText());
            ps.executeUpdate();
             JOptionPane.showMessageDialog(this, "Data Telah Di Update");
            read_table();
           IP.setText("");
            TP.setDateFormatString("");
            CBN.setActionCommand("");
            IL.setText("");
            F.setText("");
            CBS.setActionCommand("");
            
        }catch(Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+ e +"\n\n");
        }
    }//GEN-LAST:event_BTNUActionPerformed

    private void BTNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDActionPerformed
        // TODO add your handling code here:
         int ok = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus Data ini='"+IP.getText()+"'",".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
        if (ok==0){
            try{
                PreparedStatement ps = con.prepareStatement("DELETE FROM pengaduan WHERE id_pengaduan=?");
                ps.setString(1, IP.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Telah Di Delete");
                read_table();
            } catch(Exception e){
                System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
            }
        }
    }//GEN-LAST:event_BTNDActionPerformed

    private void BTNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNEActionPerformed

    private void BTNS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNS1ActionPerformed
        // TODO add your handling code here:
        String Tampilan="yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(Tampilan);
        String tgl=String.valueOf(fm.format(TP.getDate()));
        try{
            Connection c=con;
            int baris = TabelP.getRowCount();
            for (int a = 0; a < baris; a++){
                read_table();
            PreparedStatement ps=con.prepareStatement("INSERT INTO pengaduan VALUES (?,?,?,?,?,?)");
            ps.setString(1, IP.getText());
            ps.setString(2, tgl);
            ps.setString(3, CBN.getSelectedItem().toString());
            ps.setString(4, IL.getText());
             ps.setString(5, F.getText());
              ps.setString(6, CBS.getSelectedItem().toString());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data telah Tersimpan");
            }
        }catch(Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
        }
    }//GEN-LAST:event_BTNS1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan_Pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan_Pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan_Pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan_Pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan_Pengaduan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTND;
    private javax.swing.JButton BTNE;
    private javax.swing.JButton BTNIF;
    private javax.swing.JButton BTNS1;
    private javax.swing.JButton BTNS2;
    private javax.swing.JButton BTNU;
    private javax.swing.JComboBox<String> CBN;
    private javax.swing.JComboBox<String> CBS;
    private javax.swing.JTextField F;
    private javax.swing.JLabel FOTO;
    private javax.swing.JTextArea IL;
    private javax.swing.JTextField IP;
    private com.toedter.calendar.JDateChooser TP;
    private javax.swing.JTable TabelP;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
