/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apk_pengaduan_masyarakat;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
/**
 *
 * @author bri gunjat
 */
public class Tanggapan extends javax.swing.JFrame {
Connection con;
    DefaultTableModel tm;
    
    public void connect(){
        con=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/pengaduan_masyarakat","root","");
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
        }
    }
     private void id_otomatis() {
        try {
            Connection c = con;
            Statement s = c.createStatement();
            String sql = "SELECT * From tanggapan ORDER BY id_tanggapan DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String No = r.getString("id_tanggapan");
                String otomatis = "" + (Integer.parseInt(No) + 1);
                IT.setText(otomatis);
            } else {
                IT.setText("20001");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println("autonumber error");
        }
    }
      private void refreshTablemenu(){
       tm=new DefaultTableModel (null,
    new Object [] {"id_pengaduan","tgl_pengaduan","nik","isi_laporan","foto","status"});
    TabelP.setModel(tm);
    tm.getDataVector().removeAllElements();
    try{
        
        PreparedStatement s = con.prepareStatement("SELECT * FROM pengaduan");
        ResultSet r = s.executeQuery();
        while(r.next()){
            Object[] data={
               r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                 r.getString(5),
                  r.getString(6)
            };
            tm.addRow(data);
        }
    }catch (Exception e){
        System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
    
    }
    }
      private void read_table(){
       tm=new DefaultTableModel (null,
    new Object [] {"id_tanggapan","id_pengaduan","tgl_tanggapan","tanggapan","id_petugas"});
    TabelT.setModel(tm);
    tm.getDataVector().removeAllElements();
    try{
        
        PreparedStatement s = con.prepareStatement("SELECT * FROM tanggapan");
        ResultSet r = s.executeQuery();
        while(r.next()){
            Object[] data={
               r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                 r.getString(5)
            };
            tm.addRow(data);
        }
    }catch (Exception e){
        System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
    
    }
    }
       public void cbidpetugas(){
            try {
                PreparedStatement s=con.prepareStatement("SELECT*FROM petugas WHERE id_petugas");
                ResultSet r=s.executeQuery();
                while (r.next()){
                    CBIP2.addItem(r.getString("id_petugas"));
            }
        } catch (SQLException e) {
    }
        }
    /**
     * Creates new form Tanggapan
     */
    public Tanggapan() {
        initComponents();
          connect();
        id_otomatis();
        refreshTablemenu();
        cbidpetugas();
        read_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        TabelT1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelT = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        IT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CBTT = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        T = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        CBIP2 = new javax.swing.JComboBox<>();
        BTNR = new javax.swing.JButton();
        BTNU = new javax.swing.JButton();
        BTND = new javax.swing.JButton();
        BTNE = new javax.swing.JButton();
        BTNS2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        IP = new javax.swing.JTextField();
        BTNS = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelP = new javax.swing.JTable();

        TabelT1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TabelT1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TANGGAPAN");

        TabelT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID TANGGAPAN", "ID PENGADUAN", "TGL TANGGAPAN", "TANGGAPAN", "ID PETUGAS"
            }
        ));
        TabelT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelT);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("ID TANGGAPAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("ID PENGADUAN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("TGL TANGGAPAN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("TANGGAPAN");

        T.setColumns(20);
        T.setRows(5);
        jScrollPane2.setViewportView(T);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("ID PETUGAS");

        BTNR.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNR.setText("REFRESH");
        BTNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRActionPerformed(evt);
            }
        });

        BTNU.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNU.setText("UPDATE");
        BTNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUActionPerformed(evt);
            }
        });

        BTND.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTND.setText("DELETE");
        BTND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDActionPerformed(evt);
            }
        });

        BTNE.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNE.setText("EXIT");
        BTNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEActionPerformed(evt);
            }
        });

        BTNS2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNS2.setText("SEARCH");
        BTNS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNS2ActionPerformed(evt);
            }
        });

        IP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPActionPerformed(evt);
            }
        });

        BTNS.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNS.setText("SAVE");
        BTNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSActionPerformed(evt);
            }
        });

        TabelP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TabelP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(BTNS)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNU)
                                .addGap(18, 18, 18)
                                .addComponent(BTND)
                                .addGap(18, 18, 18)
                                .addComponent(BTNE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTNS2)))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(IP)
                            .addComponent(CBTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(IT, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNR)
                        .addGap(93, 93, 93))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(CBIP2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(IT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CBIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(CBTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNU)
                            .addComponent(BTND)
                            .addComponent(BTNE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNS2)
                            .addComponent(BTNS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(BTNR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDActionPerformed
        // TODO add your handling code here:
           int ok = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus Data ini='"+IT.getText()+"'",".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
        if (ok==0){
            try{
                PreparedStatement ps = con.prepareStatement("DELETE FROM tanggapan WHERE id_tanggapan=?");
                ps.setString(1, IT.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Telah Di Delete");
                read_table();
            } catch(Exception e){
                System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
            }
        }
    }//GEN-LAST:event_BTNDActionPerformed

    private void BTNS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNS2ActionPerformed

    private void IPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPActionPerformed

    private void BTNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TabelP.getModel();
        model.setRowCount(0);
        refreshTablemenu();
    }//GEN-LAST:event_BTNRActionPerformed

    private void BTNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSActionPerformed
        // TODO add your handling code here:
        String Tampilan="yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(Tampilan);
        String tgltanggapan=String.valueOf(fm.format(CBTT.getDate()));
        try {
        Connection c = con;
        int baris = TabelT.getRowCount();
        for ( int a = 0; a < baris; a++) {
            read_table();
        PreparedStatement ps = con.prepareStatement("INSERT INTO tanggapan VALUES (?,?,?,?,?)");
        ps.setString(1, IT.getText());
        ps.setString(2, IP.getText());
         ps.setString(3, tgltanggapan);
         ps.setString(4, T.getText());
         ps.setString(5, CBIP2.getSelectedItem().toString());
        ps.executeUpdate();
           JOptionPane.showMessageDialog(this, "Data telah tersimpan");
            }
        } catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_BTNSActionPerformed

    private void TabelPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPMouseClicked
        // TODO add your handling code here:
        int i = TabelP.getSelectedRow();
        if (i == -1){
            return;
        }
        String idpengaduan = (String) TabelP.getValueAt(i, 0);
        IP.setText(idpengaduan);
    }//GEN-LAST:event_TabelPMouseClicked

    private void BTNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNEActionPerformed

    private void TabelTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelTMouseClicked
        // TODO add your handling code here:
        int i = TabelT.getSelectedRow();
        if (i == -1){
            return;
        }
        String idtanggapan = (String) tm.getValueAt(i, 0);
        IT.setText(idtanggapan);
        String idpengaduan = (String) tm.getValueAt(i, 1);
        IP.setText(idpengaduan);
        String tgltanggapan = (String) tm.getValueAt(i, 2);
        CBTT.setDateFormatString(tgltanggapan);       
        String isilaporan = (String) tm.getValueAt(i, 3);
        T.setText(isilaporan);
       String idpetugas = (String) tm.getValueAt(i, 4);
        CBIP2.setActionCommand(idpetugas);
    }//GEN-LAST:event_TabelTMouseClicked

    private void BTNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUActionPerformed
        // TODO add your handling code here:
        String Tampilan="yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(Tampilan);
        String tgltanggapan=String.valueOf(fm.format(CBTT.getDate()));
        try{
            PreparedStatement ps=con.prepareStatement("UPDATE tanggapan SET id_pengaduan=?,tgl_tanggapan=?,tanggapan=?,id_petugas=? WHERE id_tanggapan=?");
            ps.setString(1, IP.getText());
            ps.setString(2, tgltanggapan);
            ps.setString(3, T.getText());
             ps.setString(4, CBIP2.getSelectedItem().toString());
              ps.setString(5, IT.getText());
            ps.executeUpdate();
             JOptionPane.showMessageDialog(this, "Data Telah Di Update");
            read_table();
           IT.setText("");
           IP.setText("");
            CBTT.setDateFormatString("");
            T.setText("");
            CBIP2.setActionCommand("");
            
        }catch(Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+ e +"\n\n");
        }
                             
    }//GEN-LAST:event_BTNUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tanggapan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTND;
    private javax.swing.JButton BTNE;
    private javax.swing.JButton BTNR;
    private javax.swing.JButton BTNS;
    private javax.swing.JButton BTNS2;
    private javax.swing.JButton BTNU;
    private javax.swing.JComboBox<String> CBIP2;
    private com.toedter.calendar.JDateChooser CBTT;
    private javax.swing.JTextField IP;
    private javax.swing.JTextField IT;
    private javax.swing.JTextArea T;
    private javax.swing.JTable TabelP;
    private javax.swing.JTable TabelT;
    private javax.swing.JTable TabelT1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
